name: stamp_image
description: Stamp_image is a library to create a watermark using any widget
version: 0.0.2
author: Yusril Rapsanjani<yuranicorp@gmail.com>
homepage: https://github.com/yusriltakeuchi/stamp_image.git

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ">=2.0.1 <=3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # To add assets to your package, add an assets section, like this:
